// REDIS EVENTS
export const REDIS_SOCKET_EVENT_SEND_NAME = "REDIS_SOCKET_EVENT_SEND_NAME";
export const REDIS_SOCKET_EVENT_EMIT_ALL_NAME =
  "REDIS_SOCKET_EVENT_EMIT_ALL_NAME";
export const REDIS_SOCKET_EVENT_EMIT_AUTHENTICATED_NAME =
  "REDIS_SOCKET_EVENT_EMIT_AUTHENTICATED_NAME";

export const REDIS_SOCKET_TAB_UPDATES = "REDIS_SOCKET_TAB_UPDATES";
